"""Add teacher_type to User and NewSurveyResponse model

Revision ID: e9dcfe727178
Revises: 
Create Date: 2026-04-19 00:35:50.835457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9dcfe727178'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_survey_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('major', sa.String(length=100), nullable=False),
    sa.Column('survey_type', sa.String(length=50), nullable=False),
    sa.Column('course_schedule', sa.String(length=10), nullable=True),
    sa.Column('course_quality', sa.String(length=10), nullable=True),
    sa.Column('knowledge_mastery', sa.String(length=10), nullable=True),
    sa.Column('other_learning', sa.Text(), nullable=True),
    sa.Column('campus_cleanliness', sa.String(length=10), nullable=True),
    sa.Column('cafeteria', sa.String(length=10), nullable=True),
    sa.Column('holiday_arrangement', sa.String(length=10), nullable=True),
    sa.Column('student_activities', sa.String(length=10), nullable=True),
    sa.Column('other_management', sa.Text(), nullable=True),
    sa.Column('teacher_responsibility', sa.String(length=10), nullable=True),
    sa.Column('teaching_satisfaction', sa.String(length=10), nullable=True),
    sa.Column('dissatisfaction_reason', sa.Text(), nullable=True),
    sa.Column('other_teaching', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_response', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_response_campus_quality'))
        batch_op.drop_index(batch_op.f('ix_survey_response_canteen_quality'))
        batch_op.drop_index(batch_op.f('ix_survey_response_gender'))
        batch_op.drop_index(batch_op.f('ix_survey_response_grade'))
        batch_op.drop_index(batch_op.f('ix_survey_response_teaching_quality'))

    op.drop_table('survey_response')
    op.drop_table('survey_template')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('teacher_type')

    op.create_table('survey_template',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('questions', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_response',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('grade', sa.VARCHAR(length=20), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=10), nullable=False),
    sa.Column('teaching_quality', sa.VARCHAR(length=10), nullable=False),
    sa.Column('canteen_quality', sa.VARCHAR(length=10), nullable=False),
    sa.Column('campus_quality', sa.VARCHAR(length=10), nullable=False),
    sa.Column('feedback', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('submitted_at', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_response', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_response_teaching_quality'), ['teaching_quality'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_response_grade'), ['grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_response_gender'), ['gender'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_response_canteen_quality'), ['canteen_quality'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_response_campus_quality'), ['campus_quality'], unique=False)

    op.drop_table('new_survey_response')
    # ### end Alembic commands ###
